### ISSUE TITLE
README confusion, *png

### ISSUE THREAD

**Issue by evanbiederstedt** [marckhoury/mars#10]
Hello

Just to clarify:

```
    ./mars -p 1 -o nasa_layout.gv graphs/nasa1824.png
```

This should be 

```
    ./mars -p 1 -o nasa_layout.gv graphs/nasa1824.gv
```

correct? These are the files in `mars/graphs`

**Comment by marckhoury** [comment]
Yes, that should be "graphs/nasa1824.gv".

**Comment by marckhoury** [comment]
I've updated the README to fix this error.

**Comment by evanbiederstedt** [comment]
@marckhoury Thanks for the help!
